In [74]:
import numpy as np

In [78]:
def diagChecker(A):
    nRows = np.shape(A)[0]
    nCols = np.shape(A)[1]
    
    for i in range(nRows):
        diagSum = 0
        nonDiagSum = 0
        
        for j in range(nCols):
            if(i==j): diagSum += abs(A[i, j])
            else: nonDiagSum += abs(A[i, j])
            
        if (diagSum < nonDiagSum): return False
    
    return True

In [79]:
A1 = np.array([[2, 1, 1],
              [1, 2, 1],
              [1, 1, 2]])

print(A1)
print("Is the matrix diagonally dominant?", diagChecker(A1))

[[2 1 1]
 [1 2 1]
 [1 1 2]]
Is the matrix diagonally dominant? True


In [80]:
A2 = np.array([[0, 1, 1],
              [1, 0, 1],
              [1, 1, 0]])

print(A2)
print("Is the matrix diagonally dominant?", diagChecker(A2))

[[0 1 1]
 [1 0 1]
 [1 1 0]]
Is the matrix diagonally dominant? False
